import { Inter } from 'next/font/google';
import './globals.css';
import ThemeProvider from '@/theme';
import { Providers } from '@/redux/providers';
import { ReduxToastify } from '@/components/reduxToastify/ReduxToastify';
import AuthLogout from '@/app/auth-logout';
import { Metadata } from 'next';
import { productFavicon } from '@/utils/constants';

const inter = Inter({ subsets: ['latin'] });
const productKeyword = process?.env?.NEXT_PUBLIC_PRODUCT_KEYWORD || 'Fynch';

export const metadata: Metadata = {
  title: `${productKeyword} App`,
  description: `Generated by ${productKeyword} app`,
  icons: {
    icon: productFavicon,
    shortcut: productFavicon,
    apple: productFavicon,
  },
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Providers>
          <AuthLogout>
            <ThemeProvider>
              <ReduxToastify />
              {children}
            </ThemeProvider>
          </AuthLogout>
        </Providers>
      </body>
    </html>
  );
}
